add partial that shows blogs related to a project page
geeksforsocialchange/gfsc-v3 pull request #350
Opened 2023-08-07 13:54 UTC by aaaaargZombies

preparatory work towards #173

## Description

- add the project specific path to a blogs front matter eg https://gfsc.studio/project/the-towers/ -> `project: the-towers`
- add the partial to project layout template `{{- partial "relatedblogs.html" . -}}`
- it will produce a `ul` of related blogs if any exist or nothing.
- not rendering anywhere as of yet because, I've added it here near the top of a project to screenshot it to prove it's working.

![towers_related_blogs](https://github.com/geeksforsocialchange/gfsc-v3/assets/6824891/c998cdd4-a120-4923-9fc3-6c78df5496a5)

@geeksforsocialchange/developers

2023-08-07 15:58 UTC, r-ferrier requested changes
I had been thinking about linking to blog posts from projects, but it makes much more sense to link to projects from blog posts!

I feel like the one-to-one relationship could be a bit restrictive and there might be situations in which we might want one blog post to link to multiple projects. For example if we create a podcast project now that we have a publications tag, we might want to link to a podcast blogpost from that project as well as whatever project the podcast was made about. 

Maybe you could change this so that the key used is `projects` and a list of strings is stored & returned instead of a single string?

2023-08-08 12:30 UTC, r-ferrier approved these changes
nice! Just one wee s missing from the archetypes. Approving so it can be merged once fixed!

2023-08-08 12:30 UTC, r-ferrier commented on archetypes/blog/index.md
> +project: ""
should be projects?

2023-08-08 12:47 UTC, aaaaargZombies commented on archetypes/blog/index.md
> +project: ""
thanks :pray:

2023-08-08 12:49 UTC, merged