356 related blog posts
geeksforsocialchange/gfsc-v3 pull request #361
Opened 2023-08-08 14:30 UTC by aaaaargZombies

Fixes #365

## Description

- a bit of refactoring
  -  `relatedBlogs` partial now just returns a slice
  - I made a `blogTeaser` partial, the intention was to use this everywhere but I needed to change the padding and header levels so
  - I made the `relatedBlogTeaser` partial
-  with related content https://436eb358.gfsc.pages.dev/project/the-towers/
- without related content https://436eb358.gfsc.pages.dev/project/placecal

@geeksforsocialchange/developers

2023-08-08 14:54 UTC, r-ferrier requested changes
This looks functionally great! Just a typo & a slight style difference that need changing and a refactoring suggestion that's optional.

2023-08-08 15:18 UTC, aaaaargZombies commented on themes/gfsc/layouts/partials/relatedBlogTeaser.html
> +  <div class="teaser__content teaser__content--related">
sure, I was in two minds about whether to do it this way or the what you're suggesting.

2023-08-10 08:43 UTC, aaaaargZombies commented
ok I think this is all the issues tidied up. some slight confusion with `.` which is the `this` of hugo but we got there in the end

2023-08-10 09:36 UTC, r-ferrier approved these changes
Nice! Looks good to me!

2023-08-10 14:05 UTC, merged